name: Build

on:
  push:
    branches: [ "home" ]
  pull_request:
    branches: [ "home" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: |
        go get github.com/twsouthwick/coredns/plugin/omada
        go generate
    - run: make
    - run: |
        mkdir dist
        cp ./coredns ./dist/coredns
    - name: Upload Dist
      uses: actions/upload-artifact@v3
      with:
        path: dist